## Run on container environment
sudo: false

language: php

php:
  - 7.0
  - hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

matrix:
  allow_failures:
    - php: hhvm
  
before_script:
  - composer update -o --prefer-source $PREFER_LOWEST

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/php-cs-fixer fix --dry-run -vv

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
